version: '3.7'
services:

    mongodb:
       image: mongo:latest
       container_name: "mongodb"
       ports: 
          - 27017:27017
 
    app:
       image: "go-template"
       ports: 
          - "1323:1323"
       environment: 
          - 'MONGODB_URI=mongodb://mongodb:27017' # mongodb://containername:port
       links: 
          - mongodb
       depends_on: 
          - mongodb